services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: trip-planner-backend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
    command: npm run dev
    restart: unless-stopped
    networks:
      - trip-planner-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: trip-planner-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tsconfig.app.json:/app/tsconfig.app.json
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - trip-planner-network

networks:
  trip-planner-network:
    driver: bridge